version: '3'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    restart: always

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  react-app:
    container_name: reactnginx
    build:
      context: ./react-nginx
      dockerfile: Dockerfile
    ports:
    - 80:80
